server:
  port: 8811

spring:
  application:
    name: boot-redisson-demo
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 20
    connect-timeout: