version: "2"

services:
  zookeeper:
    image: docker.io/ubuntu/zookeeper:edge
    container_name: zk
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/ubt_zk"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/ubuntu/kafka:latest
    container_name: kfk
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/ubt_kfk"
    environment:
      - TZ=UTC
      - ZOOKEEPER_HOST=host.docker.internal
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
