server:
  port: 8800

spring:
  application:
    name: boot-rocketmq-producer

rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}
    send-message-timeout: 10000