# docker pull apache/rocketmq:4.9.4
# docker-compose -f rocketmq-compose.yml up -d
# 启动后将 mqbroker 中的配置文件 broker.conf 中 brokerIP1 修改为本机 IP
version: '3'
services:
  #Service for nameserver
  namesrv:
    image: apache/rocketmq
    container_name: mqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: apache/rocketmq
    container_name: mqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker autoCreateTopicEnable=true -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf